
language: python
# The Travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: "3.5"
dist: trusty
services: docker

env:
  global:
    - PROJECT_NAME=bottleneck
    - REPO_DIR=bottleneck
    - BUILD_BRANCH=master
    - BUILD_COMMIT=v1.3.2

    - PIP_DISABLE_PIP_VERSION_CHECK=1
    # PyPi wheel build requirements
    - PIP_BUILD_DEP="pip~=19.0 wheel"
    - TEST_DEPENDS=pytest

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: "3.5"

  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=x86_64

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=x86_64

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=x86_64

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=x86_64

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8

cache:
  pip: true
  directories:
    - ~/Library/Caches/pip


before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
#    - echo "Skip"
    - install_run $PLAT

after_success:
  - shasum -a 256 ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
  - echo $(curl --upload-file ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl https://transfer.sh/)
