# https://packaging.python.org/en/latest/appveyor/

environment:
  global:
    PROJECT_NAME: bottleneck
    REPO_DIR: bottleneck
    BUILD_BRANCH: master
    BUILD_COMMIT: master

    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    BUILD_DEP: "pip~=19.0 wheel~=0.26.0"
    TEST_DEP: "numpy~=1.15.0 pytest"

  matrix:

    - PYTHON: "C:\\Python35-x64"
      BUILD_DEP: "--only-binary numpy numpy==1.13.3"

    - PYTHON: "C:\\Python35"
      BUILD_DEP: "--only-binary numpy numpy==1.13.3"

    - PYTHON: "C:\\Python36"
      BUILD_DEP: "--only-binary numpy numpy==1.13.3"

    - PYTHON: "C:\\Python36-x64"
      BUILD_DEP: "--only-binary numpy numpy==1.13.3"

    - PYTHON: "C:\\Python37"
      BUILD_DEP: "--only-binary numpy numpy==1.14.5"
      TEST_DEP: "numpy~=1.16.0 pytest"

    - PYTHON: "C:\\Python37-x64"
      BUILD_DEP: "--only-binary numpy numpy==1.14.5"
      TEST_DEP: "numpy~=1.16.0 pytest"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - set "WHEELDIR=%CWD%\wheels"
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install pip~=19.0 wheel~=0.26.0
  - python -m pip install %BUILD_DEP%
  # https://bugs.python.org/issue29943
  - python -c "import sys; assert not sys.version_info[:3] == (3, 6, 1)"

before_build:
  - git submodule update --init
  - git fetch origin %BUILD_BRANCH%
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%

build_script:
  - python setup.py %BUILD_GLOBAL_OPTIONS% bdist_wheel --dist-dir "%WHEELDIR%"

test_script:
  - python -m venv build\test
  - .\build\test\Scripts\activate
  - cd build
  - python -m pip install -U pip~=19.0 wheel
  - pip install %TEST_DEP%
  - pip install --no-index --no-deps --pre -f "%WHEELDIR%" %PROJECT_NAME%
  - pip install %PROJECT_NAME%
  - pip list
  - python -c "import bottleneck as bn; bn.test();"
  - cd ..

artifacts:
  - path: wheels\*
