# https://packaging.python.org/en/latest/appveyor/

environment:
  global:
    PROJECT_NAME: bottleneck
    REPO_DIR: bottleneck
    BUILD_BRANCH: master
    BUILD_COMMIT: "v1.3.2"

    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_PREFER_BINARY: "1"

    PIP_BUILD_DEP: "pip~=19.0 wheel"
    TEST_DEPENDS: "pytest"

  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - set "WHEELDIR=%CD%\wheels"
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  - python -m pip install %PIP_BUILD_DEP%
  # https://bugs.python.org/issue29943
  - python -c "import sys; assert not sys.version_info[:3] == (3, 6, 1)"

before_build:
  - git submodule update --init
  - git fetch origin %BUILD_BRANCH%
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%

build_script:
  - python -m pip wheel --no-deps ./ -w "%WHEELDIR%"

test_script:
  - python -m venv build\testenv
  - cd build
  - .\testenv\Scripts\activate
  - python -m pip install -U pip~=19.0 wheel
  - pip install %TEST_DEPENDS%
  - pip install --no-index --no-deps --pre -f "%WHEELDIR%" %PROJECT_NAME%
  - pip install %PROJECT_NAME%
  - pip list
  - python -c "import bottleneck as bn; bn.test();"
  - cd ..

artifacts:
  - path: wheels\*
